baseURL = "https://example.com"

disableKinds = ["taxonomy", "term", "section"]

[module]
    [[module.imports]]
        path = "github.com/bep/gallerydeluxe_starter"

[params]
    # Set to enable Plausible Analytics.
    plausible_domain = ""

    [params.gallerydeluxe]
        shuffle     = false
        reverse     = true
        enable_exif = false

[imaging]
    resampleFilter = "CatmullRom"
    quality        = 71
    anchor         = "smart"
    [imaging.exif]
        disableDate    = false
        disableLatLong = true
        includeFields  = 'Artist|LensModel|FNumber|ExposureTime'
