
name        = "arc"
license     = "MIT"
licenselink = "https://github.com/Sped0n/arc/blob/main/LICENSE"
description = "Fast gallery suitable for lots of images."
homepage    = "https://github.com/Sped0n/arc"
demosite    = "https://arc.sped0nwen.com/"
tags        = ["Gallery", "Responsive"]
min_version = "0.90.0"
[author]
  name     = "sped0n"
  homepage = "https://blog.sped0nwen.com"
