name: github pages

on:
  workflow_dispatch:
  push:
    branches:
    - main

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        #fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.146.5'
        extended: true
    - name: Cache Hugo resources
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.HUGO_CACHEDIR }}
          resources
        key: ${{ runner.os }}-hugo-${{ hashFiles('content/**', 'config.toml') }}
        restore-keys: |
          ${{ runner.os }}-hugo-
    - name: Build
      run: hugo --gc --minify
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./public
